//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cbmsWA
{
    using System;
    using System.Collections.Generic;
    
    public partial class BOGSalesRate
    {
        public string CurrencyId { get; set; }
        public double Rate { get; set; }
        public System.DateTime Dated { get; set; }
        public int CompanyID { get; set; }
        public Nullable<int> BureauID { get; set; }
    }
}
