//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cbmsWA
{
    using System;
    using System.Collections.Generic;
    
    public partial class BOGStockPosition
    {
        public int ID { get; set; }
        public string Details { get; set; }
        public string DetailsB { get; set; }
        public Nullable<double> GBP { get; set; }
        public Nullable<double> USD { get; set; }
        public Nullable<double> EUR { get; set; }
        public Nullable<double> CAD { get; set; }
        public Nullable<double> CHF { get; set; }
        public Nullable<double> XOF { get; set; }
        public Nullable<double> JPY { get; set; }
        public Nullable<double> ZAR { get; set; }
        public Nullable<double> NGN { get; set; }
        public Nullable<double> CNY { get; set; }
        public int ORDERBY { get; set; }
        public Nullable<int> CompanyID { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
    }
}
