//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cbmsWA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bureau
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Bureau()
        {
            this.Stocks = new HashSet<Stock>();
            this.UserDetails = new HashSet<UserDetail>();
            this.Purchases = new HashSet<Purchase>();
        }
    
        public int BureauID { get; set; }
        public int CompanyID { get; set; }
        public int AreaID { get; set; }
        public string Location { get; set; }
        public string TelNo { get; set; }
        public Nullable<double> GHS { get; set; }
        public Nullable<double> GBP { get; set; }
        public Nullable<double> USD { get; set; }
        public Nullable<double> CAD { get; set; }
        public Nullable<double> NGN { get; set; }
        public Nullable<double> CHF { get; set; }
        public Nullable<double> XOF { get; set; }
        public Nullable<double> JPY { get; set; }
        public Nullable<double> ZAR { get; set; }
        public Nullable<double> CNY { get; set; }
        public Nullable<double> EUR { get; set; }
        public Nullable<double> AUD { get; set; }
        public Nullable<double> WAU { get; set; }
        public Nullable<double> SEK { get; set; }
        public Nullable<double> GMD { get; set; }
    
        public virtual Area Area { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Stock> Stocks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserDetail> UserDetails { get; set; }
        public virtual Company Company { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Purchase> Purchases { get; set; }
    }
}
