//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cbmsWA
{
    using System;
    using System.Collections.Generic;
    
    public partial class OpenningStock
    {
        public int CurrencyId { get; set; }
        public double PurchaseAmount { get; set; }
        public Nullable<double> SalesAmount { get; set; }
        public Nullable<double> SellingRate { get; set; }
        public double PurchaseRate { get; set; }
        public System.DateTime Dated { get; set; }
        public string Username { get; set; }
    }
}
