//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cbmsWA
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockPurSum
    {
        public string CurrencyID { get; set; }
        public Nullable<double> SumPurhases { get; set; }
        public Nullable<int> CompanyID { get; set; }
        public string Active { get; set; }
    }
}
