//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cbmsWA
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserDetail
    {
        public string UserName { get; set; }
        public string EmployeeName { get; set; }
        public Nullable<int> AreaID { get; set; }
        public Nullable<int> StationID { get; set; }
        public Nullable<int> DepartmentId { get; set; }
        public string EntryBy { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public string Position { get; set; }
        public string Remark { get; set; }
        public Nullable<int> BureauID { get; set; }
    
        public virtual Area Area { get; set; }
        public virtual Department Department { get; set; }
        public virtual Station Station { get; set; }
        public virtual Bureau Bureau { get; set; }
    }
}
