//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cbmsWA
{
    using System;
    using System.Collections.Generic;
    
    public partial class VatTable
    {
        public decimal VatRate { get; set; }
        public Nullable<decimal> Vat { get; set; }
        public Nullable<decimal> NHIS { get; set; }
        public Nullable<decimal> GETFund { get; set; }
        public string Active { get; set; }
        public string UserId { get; set; }
    }
}
