//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cbmsWA
{
    using System;
    using System.Collections.Generic;
    
    public partial class WeeklyRate
    {
        public int ID { get; set; }
        public string CurrencyID { get; set; }
        public double BuyMon { get; set; }
        public double SellMon { get; set; }
        public double BuyTue { get; set; }
        public double SellTue { get; set; }
        public double BuyWed { get; set; }
        public double SellWed { get; set; }
        public Nullable<double> BuyThu { get; set; }
        public double SellThu { get; set; }
        public double BuyFri { get; set; }
        public double SellFri { get; set; }
        public double BuySat { get; set; }
        public double SellSat { get; set; }
        public double BuySun { get; set; }
        public Nullable<double> SellSun { get; set; }
        public Nullable<int> ORDERSEQ { get; set; }
        public Nullable<int> CompanyID { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
    }
}
