//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cbmsWA
{
    using System;
    using System.Collections.Generic;
    
    public partial class WEEKLYDATE
    {
        public int ID { get; set; }
        public System.DateTime DATED { get; set; }
        public string Active { get; set; }
        public Nullable<int> Days { get; set; }
    }
}
